CREATE OR REPLACE PROCEDURE w_data.DROP_TESTS()
LANGUAGE plpgsql AS $$
DECLARE
-- procedure variables
	id_to_drop int DEFAULT -1;

BEGIN
	
	CREATE TEMP TABLE temp_ids (ID_TO_DROP INT);

	INSERT INTO temp_ids (ID_TO_DROP)
	SELECT ID
	FROM w_data.MOVIMENTI
	WHERE NOTE = 'TEST' OR NOTE = 'test';

	INSERT INTO temp_ids (ID_TO_DROP)
	SELECT ID_MOV
	FROM w_data.SPESE_VARIE
	WHERE DESCRIZIONE = 'TEST' OR DESCRIZIONE = 'test';

	INSERT INTO temp_ids (ID_TO_DROP)
	SELECT ID_MOV
	FROM w_data.SPESE_FISSE
	WHERE DESCRIZIONE = 'TEST' OR DESCRIZIONE = 'test';

	INSERT INTO temp_ids (ID_TO_DROP)
	SELECT ID_MOV
	FROM w_data.ENTRATE
	WHERE DESCRIZIONE = 'TEST' OR DESCRIZIONE = 'test';

	INSERT INTO temp_ids (ID_TO_DROP)
	SELECT ID_MOV
	FROM w_data.DEBITI_CREDITI
	WHERE DESCRIZIONE = 'TEST' OR DESCRIZIONE = 'test';

	INSERT INTO temp_ids (ID_TO_DROP)
	SELECT ID_MOV
	FROM w_data.SPESE_VIAGGI
	WHERE DESCRIZIONE = 'TEST' OR DESCRIZIONE = 'test';

	INSERT INTO temp_ids (ID_TO_DROP)
	SELECT ID_MOV
	FROM w_data.SPESE_MANTENIMENTO
	WHERE DESCRIZIONE = 'TEST' OR DESCRIZIONE = 'test';

	FOR id_to_drop IN SELECT DISTINCT temp_ids.ID_TO_DROP from temp_ids
	LOOP
		
		CALL w_data.REMOVE_MOVEMENT(id_to_drop);

	END LOOP;

	DROP TABLE temp_ids;
END;
$$;