USE WALLET
GO
 
CREATE TABLE MOVIMENTI(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	DATA_MOV DATE NOT NULL,
	DATA_INS DATETIME NOT NULL,
	IMPORTO FLOAT(2) DEFAULT 0,
	DARE_AVERE BIT DEFAULT 0,
	TIPO_MOV INT NOT NULL,
	ID_PAG INT,
	NOTE VARCHAR(max) DEFAULT '')
	
CREATE TABLE MAP_PAGAMENTI(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TIPO VARCHAR(max) DEFAULT 'Carta',
	DESCRIZIONE VARCHAR(max) DEFAULT '')
	
CREATE TABLE STIPENDI(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ID_MOV INT,
	PROVENIENZA VARCHAR(max),
	MESE INT NOT NULL,
	TOTALE FLOAT(2) NOT NULL,
	NETTO FLOAT(2) DEFAULT 0,
	TRATTENUTE FLOAT(2) DEFAULT 0,
	RIMBORSO_SPESE FLOAT(2) DEFAULT 0,
	NOTE VARCHAR(max) DEFAULT '')
	
CREATE TABLE SPESE_LAVORO(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ID_MOV INT,
	DESCRIZIONE VARCHAR(max) NOT NULL,
	MESE INT NOT NULL,
	RIMBORSATO BIT DEFAULT 0,
	ID_STIPENDIO INT NULL)

CREATE TABLE SPESE_MANTENIMENTO(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ID_MOV INT NULL,
	DESCRIZIONE VARCHAR(max) NOT NULL)

CREATE TABLE SPESE_VIAGGI(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ID_MOV INT NULL,
	VIAGGIO VARCHAR(max) NOT NULL,
	DESCRIZIONE VARCHAR(max) NOT NULL)

CREATE TABLE SPESE_FISSE(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ID_MOV INT,
	DESCRIZIONE VARCHAR(max) NOT NULL,
	MESE INT NOT NULL)

CREATE TABLE MAP_SPESE_VARIE(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	DESCRIZIONE VARCHAR(max) NOT NULL)

CREATE TABLE MAP_ENTRATE(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	DESCRIZIONE VARCHAR(max) NOT NULL)

CREATE TABLE SPESE_VARIE(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ID_MOV INT,
	ID_TIPO_SPESA INT,
	DESCRIZIONE VARCHAR(max) NOT NULL)

CREATE TABLE DEBITI_CREDITI(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ID_MOV INT,
	DEBCRED BIT NOT NULL,
	DESCRIZIONE VARCHAR(max) NOT NULL,
	DESTINATARIO VARCHAR(max) DEFAULT '',
	SALDATO BIT DEFAULT 0,
	ID_MOV_SALDO INT DEFAULT '',
	DATA_SALDO DATETIME)

CREATE TABLE ENTRATE(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ID_MOV INT,
	ID_TIPO_ENTRATA INT NOT NULL,
	DESCRIZIONE VARCHAR(max) NOT NULL)
	
CREATE TABLE MAP_TABELLE(				
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(30) NOT NULL,
	DESCRIZIONE VARCHAR(max) NOT NULL,
	RUOLO VARCHAR(10) NOT NULL)

CREATE TABLE QLIK_USERS(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	RUOLO VARCHAR(10),
	USERNAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(MAX) NOT NULL,
	NOTE VARCHAR(50) DEFAULT NULL)

CREATE TABLE MAP_MOVIMENTI(
	[ID] INT IDENTITY(1,1) PRIMARY KEY,
	[DESCRIZIONE] [varchar](max) NOT NULL,
	[NOME_TABELLA] [varchar](max) NOT NULL,
	[TIPO_MOVIMENTO] [varchar](max) NOT NULL)

CREATE TABLE UTENTI(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	USERNAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
	RUOLO VARCHAR(10) NOT NULL)