SELECT 
    'ALTER TABLE [' +  OBJECT_SCHEMA_NAME(parent_object_id) +
    '].[' + OBJECT_NAME(parent_object_id) + 
    '] DROP CONSTRAINT [' + name + ']'
FROM sys.foreign_keys
--WHERE referenced_object_id = object_id('SPESE_FISSE')

ALTER TABLE [dbo].[MOVIMENTI] DROP CONSTRAINT [FK__MOVIMENTI__ID_PA__4E1E9780]
ALTER TABLE [dbo].[STIPENDI] DROP CONSTRAINT [FK__STIPENDI__ID_MOV__51EF2864]
ALTER TABLE [dbo].[SPESE_LAVORO] DROP CONSTRAINT [FK__SPESE_LAV__ID_MO__589C25F3]
ALTER TABLE [dbo].[SPESE_LAVORO] DROP CONSTRAINT [FK__SPESE_LAV__ID_ST__5A846E65]
ALTER TABLE [dbo].[SPESE_FISSE] DROP CONSTRAINT [FK__SPESE_FIS__ID_MO__5D60DB10]
ALTER TABLE [dbo].[SPESE_VARIE] DROP CONSTRAINT [FK__SPESE_VAR__ID_MO__61316BF4]
ALTER TABLE [dbo].[SPESE_VARIE] DROP CONSTRAINT [FK__SPESE_VAR__ID_TI__6225902D]
ALTER TABLE [dbo].[DEBITI_CREDITI] DROP CONSTRAINT [FK__DEBITI_CR__ID_MO__6501FCD8]